spring:
  application:
    name: formulario-service
  data:
    mongodb:
      uri: mongodb://mongo:27017/formulariosdb
      auto-index-creation: true

server:
  port: 8080
  # NOTA: Eliminamos context-path para simplificar en Docker

logging:
  level:
    com.example.formulario_service: INFO
    org.springframework.web.reactive: INFO

app:
  security:
    api-key: "formulario-api-key-2024"
    enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
